// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *APIOauth2Client) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IdentityGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IdentityUser) Hub() {}
