apiVersion: ovh.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: ovh-credentials
      namespace: crossplane-system
      key: credentials
