// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *CephACL) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NashaPartition) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NashaPartitionAccess) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NashaPartitionSnapshot) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServerNetworking) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServerRebootTask) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServerReinstallTask) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServerUpdate) Hub() {}
