// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EFSShareSnapshotInitParameters struct {

	// Snapshot description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Snapshot name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Share ID
	ShareID *string `json:"shareId,omitempty" tf:"share_id,omitempty"`
}

type EFSShareSnapshotObservation struct {

	// Snapshot creation date
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Snapshot description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Snapshot name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Snapshot path
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Share ID
	ShareID *string `json:"shareId,omitempty" tf:"share_id,omitempty"`

	// Snapshot status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Snapshot type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EFSShareSnapshotParameters struct {

	// Snapshot description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Snapshot name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Service name
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Share ID
	// +kubebuilder:validation:Optional
	ShareID *string `json:"shareId,omitempty" tf:"share_id,omitempty"`
}

// EFSShareSnapshotSpec defines the desired state of EFSShareSnapshot
type EFSShareSnapshotSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EFSShareSnapshotParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EFSShareSnapshotInitParameters `json:"initProvider,omitempty"`
}

// EFSShareSnapshotStatus defines the observed state of EFSShareSnapshot.
type EFSShareSnapshotStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EFSShareSnapshotObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EFSShareSnapshot is the Schema for the EFSShareSnapshots API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ovh}
type EFSShareSnapshot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.shareId) || (has(self.initProvider) && has(self.initProvider.shareId))",message="spec.forProvider.shareId is a required parameter"
	Spec   EFSShareSnapshotSpec   `json:"spec"`
	Status EFSShareSnapshotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EFSShareSnapshotList contains a list of EFSShareSnapshots
type EFSShareSnapshotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EFSShareSnapshot `json:"items"`
}

// Repository type metadata.
var (
	EFSShareSnapshot_Kind             = "EFSShareSnapshot"
	EFSShareSnapshot_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EFSShareSnapshot_Kind}.String()
	EFSShareSnapshot_KindAPIVersion   = EFSShareSnapshot_Kind + "." + CRDGroupVersion.String()
	EFSShareSnapshot_GroupVersionKind = CRDGroupVersion.WithKind(EFSShareSnapshot_Kind)
)

func init() {
	SchemeBuilder.Register(&EFSShareSnapshot{}, &EFSShareSnapshotList{})
}
