// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Project) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectContainerregistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectContainerregistryIAM) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectContainerregistryIPRestrictionsManagement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectContainerregistryIPRestrictionsRegistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectContainerregistryOidc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectContainerregistryUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseDatabase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseIntegration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseIPRestriction) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseKafkaACL) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseKafkaSchemaregistryacl) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseKafkaTopic) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseLogSubscription) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseM3DbNamespace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseM3DbUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseMongodbPrometheus) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseMongodbUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseOpensearchPattern) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseOpensearchUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabasePostgresqlConnectionPool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabasePostgresqlUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabasePrometheus) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseRedisUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectDatabaseValkeyUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectFailoverIPAttach) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectGateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectGatewayInterface) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectInstance) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectInstanceSnapshot) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectKube) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectKubeIprestrictions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectKubeNodepool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectKubeOidc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectNetworkPrivate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectNetworkPrivateSubnet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectNetworkPrivateSubnetV2) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectRegionLoadbalancerLogSubscription) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectRegionStoragePresign) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectSSHKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectUserS3Credential) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectUserS3Policy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectVolumeBackup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectWorkflowBackup) Hub() {}
