// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProjectContainerregistryIPRestrictionsManagementInitParameters struct {

	// List your IP restrictions applied on artifact manager component
	IPRestrictions []map[string]*string `json:"ipRestrictions,omitempty" tf:"ip_restrictions,omitempty"`

	// RegistryID
	RegistryID *string `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type ProjectContainerregistryIPRestrictionsManagementObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List your IP restrictions applied on artifact manager component
	IPRestrictions []map[string]*string `json:"ipRestrictions,omitempty" tf:"ip_restrictions,omitempty"`

	// RegistryID
	RegistryID *string `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type ProjectContainerregistryIPRestrictionsManagementParameters struct {

	// List your IP restrictions applied on artifact manager component
	// +kubebuilder:validation:Optional
	IPRestrictions []map[string]*string `json:"ipRestrictions,omitempty" tf:"ip_restrictions,omitempty"`

	// RegistryID
	// +kubebuilder:validation:Optional
	RegistryID *string `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// Service name
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

// ProjectContainerregistryIPRestrictionsManagementSpec defines the desired state of ProjectContainerregistryIPRestrictionsManagement
type ProjectContainerregistryIPRestrictionsManagementSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectContainerregistryIPRestrictionsManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectContainerregistryIPRestrictionsManagementInitParameters `json:"initProvider,omitempty"`
}

// ProjectContainerregistryIPRestrictionsManagementStatus defines the observed state of ProjectContainerregistryIPRestrictionsManagement.
type ProjectContainerregistryIPRestrictionsManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectContainerregistryIPRestrictionsManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectContainerregistryIPRestrictionsManagement is the Schema for the ProjectContainerregistryIPRestrictionsManagements API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ovh}
type ProjectContainerregistryIPRestrictionsManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipRestrictions) || (has(self.initProvider) && has(self.initProvider.ipRestrictions))",message="spec.forProvider.ipRestrictions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.registryId) || (has(self.initProvider) && has(self.initProvider.registryId))",message="spec.forProvider.registryId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   ProjectContainerregistryIPRestrictionsManagementSpec   `json:"spec"`
	Status ProjectContainerregistryIPRestrictionsManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectContainerregistryIPRestrictionsManagementList contains a list of ProjectContainerregistryIPRestrictionsManagements
type ProjectContainerregistryIPRestrictionsManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectContainerregistryIPRestrictionsManagement `json:"items"`
}

// Repository type metadata.
var (
	ProjectContainerregistryIPRestrictionsManagement_Kind             = "ProjectContainerregistryIPRestrictionsManagement"
	ProjectContainerregistryIPRestrictionsManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectContainerregistryIPRestrictionsManagement_Kind}.String()
	ProjectContainerregistryIPRestrictionsManagement_KindAPIVersion   = ProjectContainerregistryIPRestrictionsManagement_Kind + "." + CRDGroupVersion.String()
	ProjectContainerregistryIPRestrictionsManagement_GroupVersionKind = CRDGroupVersion.WithKind(ProjectContainerregistryIPRestrictionsManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectContainerregistryIPRestrictionsManagement{}, &ProjectContainerregistryIPRestrictionsManagementList{})
}
