// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Cloudproject) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DedicatedCloud) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DedicatedCloudDatacenter) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DedicatedServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DedicatedServerInterface) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Iploadbalancing) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IPv6) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IPv6RoutedSubrange) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ovhcloudconnect) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vrackservices) Hub() {}
